### ISSUE TITLE
RamID for ESS SetPoint

### ISSUE THREAD

**Issue by jliegner** [martiby/ess#1]
Hallo,

mir ist in Ihrem Code eine Schwachstelle aufgefallen. Sie gehen davon aus, dass das Register zum Setzen der Power (EssSetPoint) 131 ist. Ich kann ihnen aus eigener Erfahrung sagen, dass das nur manchmal so ist. Ich habe 3 Multiplus im Einsatz beim 5000 ist es anders als beim 3000er. Das ist eventuell auch Firmewareabhängig. Auf alle Fälle sollten sie die Ermittlung der RamId für den ESS Assitenten noch implementieren, wie bei Victron beschrieben:
--------------------------------------------------------------------------------------------
<html><body>
<h4 id="working_with_ram_ids_to_address_assistants">3.6.2 Working with RAM IDs to address Assistants</h4>
<div class="level4">

<p>
Use RAM ID 128 and higher. Every RAM ID is a word (2 bytes)
</p>

<p>
The assistant RAM will be filled from ID 128 with ‘assistant RAM 
records’. Each record starts with a word that contains the AssistantID 
and the size of the record, and then a number of AssistantRAM words.
</p>
<div class="table sectionedit18">

RAM ID | contents
-- | --
128 | ID_Size (1st Assistant)
129 | 1st AssistantRAM0
130 | 1st AssistantRAM1
… | …
RAMn | 1st AssistantRAMn
RAMn+1 | ID_Size (2nd Assistant in this VE.Bus device, if any)
RAMn+2 | 2nd AssistantRAM0
RAMn+3 | 2nd AssistantRAM1
etcetera

</div>

<p>
The ID_Size word contains 0xZZZY, where:
</p>
<ul>
<li class="level1"><div class="li"> ZZZ = the Assistant ID. This is where you can recognize the function of the assistant (ESS ID = 5)</div>
</li>
<li class="level1"><div class="li"> Y = the number of ramIDs that will 
follow after the ID_Size. At the moment of writing this is 2 for the ESS
 Assistant version. This can be increased in future releases if more 
parameters become available.</div>
</li>
</ul>

<p>
So you have to scan the Assistant RAM records by looking at each ID_size record.
</p>

</div>

<h4 id="ess_assistant_ram_ids">3.6.3 ESS Assistant RAM IDs</h4>
<div class="level4">

<p>
The RAM ids of the ESS Assistant are:
</p>
<ul>
<li class="level1"><div class="li"> AssistantRAM0: AC-in setpoint in Watts (positive for charge, negative for discharge)</div>
</li>
<li class="level1"><div class="li"> AssistantRAM1-bit 0: 'disable charge'-flag</div>
</li>
<li class="level1"><div class="li"> AssistantRAM1-bit 1: 'disable feed-in'-flag</div>
</li>
</ul>

<p>
Above information is an addendum to the 'Interfacing with VE.Bus products' document. Available from our <a href="https://www.victronenergy.com/support-and-downloads/whitepapers" class="urlextern" title="https://www.victronenergy.com/support-and-downloads/whitepapers">whitepapers</a>.
</p>

</div>
</body>
</html>3.6.2 Working with RAM IDs to address Assistants

Use RAM ID 128 and higher. Every RAM ID is a word (2 bytes)

The assistant RAM will be filled from ID 128 with ‘assistant RAM records’. Each record starts with a word that contains the AssistantID and the size of the record, and then a number of AssistantRAM words.
RAM ID 	contents
128 	ID_Size (1st Assistant)
129 	1st AssistantRAM0
130 	1st AssistantRAM1
… 	…
RAMn 	1st AssistantRAMn
RAMn+1 	ID_Size (2nd Assistant in this VE.Bus device, if any)
RAMn+2 	2nd AssistantRAM0
RAMn+3 	2nd AssistantRAM1
etcetera

The ID_Size word contains 0xZZZY, where:

    ZZZ = the Assistant ID. This is where you can recognize the function of the assistant (ESS ID = 5)
    Y = the number of ramIDs that will follow after the ID_Size. At the moment of writing this is 2 for the ESS Assistant version. This can be increased in future releases if more parameters become available.

So you have to scan the Assistant RAM records by looking at each ID_size record.
3.6.3 ESS Assistant RAM IDs

The RAM ids of the ESS Assistant are:

    AssistantRAM0: AC-in setpoint in Watts (positive for charge, negative for discharge)
    AssistantRAM1-bit 0: 'disable charge'-flag
    AssistantRAM1-bit 1: 'disable feed-in'-flag

Above information is an addendum to the 'Interfacing with VE.Bus products' document. Available from our [whitepapers](https://www.victronenergy.com/support-and-downloads/whitepapers).

-------------------------------------------------------------------------------------------------------------

Ich habe etwas ähnliches in C++ implementiert aber noch nicht veröffentlicht. Bei mir sieht die Ermittlung des richtigen Registers so aus:

// ermittelt die Adresse der Ram Variable für die 
// ESS SetPoint Funktion
bool Mk2::CheckEssAssistent()
{
  uEssSetPointRamVar=0;
  uint16_t nRv=128;
  for (int n=0; n<8; n++)
    {
    uint16_t u=GetRamVar(nRv);
    if (u==0)
      return false;

    // der ESS Assistent hat die Id 5 
    // der ESS Vorgänger HUB4 die Id 3
    if ((u & 0xfff0)==0x0050 || (u & 0xfff0)==0x0030)
      {
      uEssSetPointRamVar=nRv+1;
      return true;
      }
    nRv+=1 + (u & 0x0f);
    }
  return false;
}

**Comment by martiby** [comment]
Vielen Dank für die Anmerkung ! Alle Nachbauten verwenden MP2 3000 mit aktueller Firmware, da ist das bisher noch kein Thema gewesen. Werde ich noch einbauen.

wakeup() und sleep() dürften für Deine Implementierung evt. interessant sein, die habe ich nirgends dokumentiert gefunden und deshalb zwischen FTDI und CPU im MK3 mitgelesen.

Vielen Dank für Dein Feedback.

**Comment by jliegner** [comment]
Vielen Dank für die Antwort.
Ich bin mir jetzt nicht sicher wo der Unterschied bezüglich des Sleep/Wakeup ist, aber ich mache das mit dem dokumentierten 
Messages
``````
"5 Switch and input current settigs"

Variant 2: <Flags[7]>=1 
 
<Switch state>  Meaning 
1  Charger only 
2  Inverter only 
3  On 
4  Off 

Command:  ‘S’ <Switch state> <Lo(Limit)> <Hi(Limit)> 0x01 <Flags>  [<Reserved> <FlagsExt0> <EEPROM flags>]  
Reply:   ‘S’ 

Making Limit>=0x8000 will result in the input current setpoint being ignored

z.B.:

  uint8_t vbuf[32];
  vbuf[0]=07;
  vbuf[1]=0xff;
  vbuf[2]='S';
  vbuf[3]=swState;
  vbuf[4]=inputCurrent & 0xff;
  vbuf[5]=(inputCurrent>>8) & 0xff;
  vbuf[6]=0x01;
  vbuf[7]=0x80;
  send(vbuf);

  (send berechnet bei mir Länge und CS selbst, inputCurrent steht auf 0x8000 und wird damit ignoriert)

``````
Nach einem OFF schalten sich alle Relais im Multiplus aus und auch alle LEDs, nach einem ON macht der Victron wieder seine Relais-Klapper-Orgie und reagiert wieder auf die SetPoint Vorgaben.

**Comment by martiby** [comment]
Den Scan der RamID habe ich implementiert, Vielen Dank nochmal für den Hinweis !

Der Switch State Befehl hat bei mir nicht funktioniert. In der Software verwende ich die Befehle wie sie das VenusOS an den MP2 sendet.
