### ISSUE TITLE
SOC von MP2 ist verdoppelt

### ISSUE THREAD

**Issue by martin2day2** [martiby/ess#2]
Hallo Martin,

der MP2 zeit den gemessen SOC verdoppelt an. Um in der Software den richtigen Wert zu erhalten muss hier noch halbiert werden.
Ich habe dies in vebus.py Zeile 220 erledigt.
`'soc': soc}` geändert in `'soc':soc / 2}`

Gruß Martin

**Comment by martiby** [comment]
Danke für den Hinweis, wurde geändert.
