### ISSUE TITLE
Pylontech US5000 BMS

### ISSUE THREAD

**Issue by mgerhard74** [martiby/ess#3]
Hallo Martin,
ich baue gerade das System mit einer Pylontech US5000 nach. Als Energiezähler wird  ein EVU Smartmeter [Lesekopf ](http://www.mitterbaur.at/amis-leser.html) verwendet, dieser ist auch schon in Meterhub intergriert. (Rest Schnittstelle)

Folgendes ist mir bisher aufgefallen:
Die Installation von "pip install pyserial" ist nicht erwähnt, das log Verzeichnis habe ich manuell anlegen müssen und die Angabe der IP:Port des Webservice sollte im conifg.py definiert werden.

Das BMS der US5000 liefert nach
TX: b'~20024642E00202FD33\r'
nur
RX: b'\x00\x00\x00\x00'
zurück. Ich habe auch noch 9600Baud probiert, gleiches Verhalten.

Hast du dazu eine Doku oder einen Vorschlag, was ich probieren könnte?

Danke,
Gerhard

**Comment by martiby** [comment]
Hallo Gerhard,

Danke für das Feedback.

>Die Installation von "pip install pyserial" ist nicht erwähnt,

Stimmt, habe ich in den requirements hinzugefügt.

>das log Verzeichnis habe ich manuell anlegen müssen

Kann eigentlich nicht sein, das log Verzeichnis wird automatisch angelegt. (ess.py Zeile 10) Auf was für einer Hardware hast Du hast Du das System laufen ? 

>der IP:Port des Webservice sollte im conifg.py definiert werden.

Pull request :-)

Ich habe die US2000 und 3000 mit den Infos aus:  "PYLON LFP Battery communication protocol - RS485 V2.8 20161216.pdf"
implementiert. 

Viele Grüße,
Martin

**Comment by mgerhard74** [comment]
Hallo Martin,
meine Hardware ist ein Raspberry Pi 1B.
Ich versuche die RS485 Doku zur US5000 zu bekommen.
Danke und lg Gerhard

**Comment by mgerhard74** [comment]
Hallo Martin,
scheinbar hatte ich ein RS485 Verkabelungsproblem. Es gibt kein GND für RS485, nur A und B. 120Ohm habe ich auch zwischen A und B angeschlossen.
Nun erhalte ich scheinbar "unglaubwürdige" Daten, SOC mit 76% stimmt, aber der Rest nicht:

ERROR    error max voltage at bms {'error': None, 'u': 65.535, 'i': 289.5, 't': 16.9, 'soc': 76, 'soc_low': 76, 'soc_high': 76, 'pack_u': [65.535], 'pack_i': [289.5], 'pack_t': [16.9], 'pack_soc': [76], 'pack_cycle': [65535]}

u , pack_u und pack_cycle je 65535, also FFFF.

`pi@ESS:~/ess $ sudo python demo_pylontech.py
{'serial': 'Y220817C50440540'}
TX: b'~200246510000FDAC\r'
RX: b'~20024600C04055533530303000000000010350796C6F6E2D2D2D2D2D2D2D2D2D2D2D2D2D2D2DEFC5\r'
{'device': 'US5000', 'version': '1.3', 'manufacturer': 'Pylon'}
0 {'u_cell': (3300, 3310, 3308, 3302, 3303, 3315, 3298, 3315, 3305, 3303, 3315, 3305, 3303, 3305, 3303), 't': [17.5, 16.1, 15.6, 15.4, 15.2], 'cycle': 65535, 'i': 289.7, 'u': 65.535, 'q': 49590, 'q_total': 65284, 'soc': 76}
`

Vom Multiplus erhalte ich DC 49,4Volt.
Ich habe bei Pylontech um die RS485 Doku zur US5000 angefragt.
lg Gerhard

**Comment by martiby** [comment]
Hallo Gerhard,

diese einfachen 2..5€ USB RS485 Wandler erzeugen keine sauberen Pegel, selbst geschenkt am besten erst gar nicht damit anfangen. https://www.mikrocontroller.net/topic/519031

Wir haben gute Erfahrungen mit diesem Typ: https://www.waveshare.com/usb-to-rs485.htm

Viele Grüße,
Martin

**Comment by mgerhard74** [comment]
Hallo Martin,
ich verwende den Waveshare Wandler. Die Daten sind nun reproduzierbar die gleichen. Ich habe bis gestern Abend GND des CAN Signales an der gleichen Pylontech Buchse verwendet. An der Buchse ist scheinbar kein GND für RS485, nur A und B. Ich habe einen 120Ohm Widerstand zw A und B.
lg Gerhard

**Comment by mgerhard74** [comment]
Hallo Martin,
auch mein Nachbau mit einer US5000 Batterie läuft, ev kommt noch eine Zweite. Danke auch von mir fürs Teilen deiner Projekte. 
Das BMS der US5000 liefert um 4 Byte mehr beim Analog value packet, habe mich mit Try and Error rangetastet, es gibt keine BMS Doku für die US5000.

Hier meine Änderungen für das US5000 BMS:
pylontech.py:
   current, voltage, q1, id, q1_total, d['cycle'] = struct.unpack_from(">hHHbHH", frame, p + 44)   #p+42 war Standard für US3000
    d['i'] = current / 10
    d['u'] = voltage / 1000
 
    if id == 4:   #für US3000/5000
        p = p + 44 + 11    #42 war Standard für US3000
        d['q'] = struct.unpack(">I", b'\x00' + frame[p:p+3])[0]
        p += 3
        d['q_total'] = struct.unpack(">I", b'\x00' + frame[p:p + 3])[0]

Sorry, dass ich mich mit Pull requests noch nicht auskenne....

lg aus Oberöstereich, Gerhard

**Comment by gaborfri** [comment]
sorry für die dumme Frage: wie muss die Verkabelung zwischen US5000 und dem waveshare RS485 aussehen? Welchen der Ports am Pylontech muss ich verwenden RS485 oder doch CAN?
bisher gehe ich davon aus das Pin4 auf H und Pin5 auf L gehen muss und ggf. Pin6 auf GND

**Comment by mgerhard74** [comment]
US5000: Buchse "A/CAN" Pin 7 und 8 auf A und B des Waveshare Converters. Ich habe keine Masse und keinen Abschlusswiderstand verwendet, nur die zwei Adern.

**Comment by gaborfri** [comment]
ok das passt. Nun kommen doch noch gleich weitere Fragen:
Muss für den UC5000 noch etwas angepasst werden?
und wie binde ich einen Shelly 3EM ein? Es gibt eine API-URL, aber wo konfiguriere ich die abzufragenden Attribute?

**Comment by mgerhard74** [comment]
Für die US5000 Batterie musst du wie von mir oben beschrieben die pylontech.py abändern.
Ich habe meinen Smartmeter Reader, welcher eine Rest-Schnittstelle bereitstellt so eingebunden:

Projekt meterhub, app.py:

`        # AMIS READER

        try:
            self.api_response = requests.get('http://10.0.0.152/rest')
            self.amis = self.api_response.json()
            if self.amis['saldo'] == 0:
                self.amis['saldo']=1
            data['grid_imp_eto'] = self.amis['saldo']
            data['grid_exp_eto'] = self.amis['saldo']
            data['grid_p'] = self.amis['saldo']

        except:
            data['grid_p'] = 1
`

Wenn der Shelly auch eine Rest-Schnittstelle bereitstellt, copy and paste, try and error.
good luck,
Gerhard

**Comment by mgerhard74** [comment]
Opened a pull request
